[2024-09-10T15:46:19.333+0530] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-10T15:46:19.346+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: beam_etl_dag_with_credentials.run_beam_pipeline manual__2024-09-10T10:16:15.872296+00:00 [queued]>
[2024-09-10T15:46:19.356+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: beam_etl_dag_with_credentials.run_beam_pipeline manual__2024-09-10T10:16:15.872296+00:00 [queued]>
[2024-09-10T15:46:19.357+0530] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-10T15:46:19.382+0530] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_beam_pipeline> on 2024-09-10 10:16:15.872296+00:00
[2024-09-10T15:46:19.387+0530] {standard_task_runner.py:72} INFO - Started process 192809 to run task
[2024-09-10T15:46:19.392+0530] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'beam_etl_dag_with_credentials', 'run_beam_pipeline', 'manual__2024-09-10T10:16:15.872296+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/beam_etl_dag.py', '--cfg-path', '/tmp/tmpvy78wj36']
[2024-09-10T15:46:19.393+0530] {standard_task_runner.py:105} INFO - Job 71: Subtask run_beam_pipeline
[2024-09-10T15:46:19.451+0530] {task_command.py:467} INFO - Running <TaskInstance: beam_etl_dag_with_credentials.run_beam_pipeline manual__2024-09-10T10:16:15.872296+00:00 [running]> on host PG0392KD.springernature.com
[2024-09-10T15:46:19.562+0530] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='beam_etl_dag_with_credentials' AIRFLOW_CTX_TASK_ID='run_beam_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2024-09-10T10:16:15.872296+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-10T10:16:15.872296+00:00'
[2024-09-10T15:46:19.563+0530] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-10T15:46:19.563+0530] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-10T15:46:19.564+0530] {logging_mixin.py:190} INFO - Current task name:run_beam_pipeline state:running start_date:2024-09-10 10:16:19.347152+00:00
[2024-09-10T15:46:19.564+0530] {logging_mixin.py:190} INFO - Dag name:beam_etl_dag_with_credentials and current dag run status:running
[2024-09-10T15:46:19.564+0530] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-10T15:46:19.956+0530] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/sst7260/airflow_projects/project1/dags/beam_etl_dag.py", line 43, in run_beam_pipeline
    options.view_as(beam.options.pipeline_options.GoogleCloudOptions).credentials = credentials
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/apache_beam/options/pipeline_options.py", line 495, in __setattr__
    raise AttributeError(
AttributeError: 'GoogleCloudOptions' object has no attribute 'credentials'
[2024-09-10T15:46:19.972+0530] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-10T15:46:19.973+0530] {logging_mixin.py:190} INFO - Task start:2024-09-10 10:16:19.347152+00:00 end:2024-09-10 10:16:19.972599+00:00 duration:0.625447
[2024-09-10T15:46:19.973+0530] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): run_beam_pipeline> dag:<DAG: beam_etl_dag_with_credentials> dagrun:<DagRun beam_etl_dag_with_credentials @ 2024-09-10 10:16:15.872296+00:00: manual__2024-09-10T10:16:15.872296+00:00, state:running, queued_at: 2024-09-10 10:16:15.949971+00:00. externally triggered: True>
[2024-09-10T15:46:19.973+0530] {logging_mixin.py:190} INFO - Failure caused by 'GoogleCloudOptions' object has no attribute 'credentials'
[2024-09-10T15:46:19.973+0530] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=beam_etl_dag_with_credentials, task_id=run_beam_pipeline, run_id=manual__2024-09-10T10:16:15.872296+00:00, execution_date=20240910T101615, start_date=20240910T101619, end_date=20240910T101619
[2024-09-10T15:46:20.018+0530] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-10T15:46:20.018+0530] {standard_task_runner.py:124} ERROR - Failed to execute job 71 for task run_beam_pipeline ('GoogleCloudOptions' object has no attribute 'credentials'; 192809)
Traceback (most recent call last):
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/sst7260/airflow_projects/project1/dags/beam_etl_dag.py", line 43, in run_beam_pipeline
    options.view_as(beam.options.pipeline_options.GoogleCloudOptions).credentials = credentials
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/apache_beam/options/pipeline_options.py", line 495, in __setattr__
    raise AttributeError(
AttributeError: 'GoogleCloudOptions' object has no attribute 'credentials'
[2024-09-10T15:46:20.050+0530] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-10T15:46:20.060+0530] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-10T15:46:20.060+0530] {local_task_job_runner.py:245} INFO - ::endgroup::
